repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    -   id: fmt
        args: ['--manifest-path', '2024/aoc-rust-2024/Cargo.toml', '--']
    -   id: cargo-check
        args: ['--manifest-path', '2024/aoc-rust-2024/Cargo.toml', '--']
    -   id: clippy
        args: ['--manifest-path', '2024/aoc-rust-2024/Cargo.toml', '--']
