[package]
name = "aoc-rust-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = { version = "0.54.0", features = ["proc_macro"] }
itertools = "0.13.0"
partitions = "0.2.4"
regex = "1.11.1"
trie-rs = "0.4.2"
